[package]
name = "blasstar"
version = "0.1.0"
edition = "2024"
readme = "Readme.md"
description = "a 2d schmup game"

[dependencies]
anyhow = { version = "1.0.97", features = ["backtrace"] }
sdl3 = { version = "0.14.16", features = ["ttf" ] }
